// Dados do CRM - Sincronizado em 2026-02-24 18:49:31
// Total: 95 propostas
// Coluna Status: baseada na Probabilidade (100%=Fechada, 0%=Perdida, 60%+=Pendente, 40%+=Enviada, Lead)

const propostas = [
    {
        "id": 1,
        "vendedor": "Guilherme",
        "numeroProposta": "1",
        "cliente": "Vanessa Guimarães",
        "contato": "Vanessa",
        "telefone": "41 99906 5076",
        "email": "",
        "servico": "Tour Virtual",
        "followUp": "",
        "localizacao": "Fernandes Pinheiro",
        "dataProposta": "27/02/2025",
        "dataFechamento": "27/02/2025",
        "valor": 3500.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 2,
        "vendedor": "Marcelo",
        "numeroProposta": "05202530.0",
        "cliente": "Ivilyn",
        "contato": "ivilyn",
        "telefone": "(41)99684-8294",
        "email": "",
        "servico": "Scan To BIM",
        "followUp": "21-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 35000.0,
        "probabilidade": "60%",
        "status": "Pendente",
        "observacao": ""
    },
    {
        "id": 3,
        "vendedor": "Marcelo",
        "numeroProposta": "06202531.0",
        "cliente": "André Canoas",
        "contato": "André Canoas",
        "telefone": "(11)97150-6623",
        "email": "",
        "servico": "LPC com lidar + produto",
        "followUp": "13-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 19980.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 4,
        "vendedor": "Marcelo",
        "numeroProposta": "06202532.0",
        "cliente": "Max Pilarzinho",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento e Laudo",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 15980.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 5,
        "vendedor": "Guilherme",
        "numeroProposta": "06202534.0",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "28/07/2025",
        "dataFechamento": "28/07/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 6,
        "vendedor": "Guilherme",
        "numeroProposta": "6202533.0",
        "cliente": "Palacete do pinho",
        "contato": "Renato Barbizan",
        "telefone": "(41)99712-9402",
        "email": "",
        "servico": "Scan To BIM",
        "followUp": "",
        "localizacao": " Irati-PR",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 38000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 7,
        "vendedor": "",
        "numeroProposta": "7202535.0",
        "cliente": "Priscila",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento Abranches",
        "followUp": "16-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 4800.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 8,
        "vendedor": "",
        "numeroProposta": "7202536.0",
        "cliente": "Amanda",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Prédio Guaira",
        "followUp": "16-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 23000.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 9,
        "vendedor": "Marcelo",
        "numeroProposta": "072025.38.0",
        "cliente": "Cidatec",
        "contato": "Marcelo",
        "telefone": "N/A",
        "email": "",
        "servico": "Voo + cadastro de Vaga",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 3800.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 10,
        "vendedor": "Allana ",
        "numeroProposta": "07202539.1",
        "cliente": "Ana Paula Arquiteta",
        "contato": "Ana Paula",
        "telefone": "",
        "email": "",
        "servico": "Scan To BIM",
        "followUp": "13-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 21705.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 11,
        "vendedor": "Guilherme",
        "numeroProposta": "7202537.0",
        "cliente": "Acompanhamento Museu",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "22-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 3980.0,
        "probabilidade": "60%",
        "status": "Pendente",
        "observacao": ""
    },
    {
        "id": 12,
        "vendedor": "",
        "numeroProposta": "7202540.0",
        "cliente": "Estudo de massa",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Estudo de massa",
        "followUp": "25-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 6880.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 13,
        "vendedor": "",
        "numeroProposta": "7202537.0",
        "cliente": "Topografica Santa Candida",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento topografico",
        "followUp": "24-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 3200.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 14,
        "vendedor": "",
        "numeroProposta": "07202541.0",
        "cliente": "Potencial S.A",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento topografico",
        "followUp": "31-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 135000.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 15,
        "vendedor": "",
        "numeroProposta": "07202542.1",
        "cliente": "Encompi",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento topografico",
        "followUp": "28-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 5000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 16,
        "vendedor": "",
        "numeroProposta": "07202543.0",
        "cliente": "Patricia",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Levantamento Chacará 3 Meninos",
        "followUp": "29-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 8000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 17,
        "vendedor": "",
        "numeroProposta": "07202544.0",
        "cliente": "Ricardo",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Campo Magro",
        "followUp": "29-jul.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 7000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 18,
        "vendedor": "Allana",
        "numeroProposta": "08202545.0",
        "cliente": "Oliveira e Araujo",
        "contato": "Alisson Caliman",
        "telefone": "(62)99449-6145",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": " Hospital -Ponta Grossa",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 13800.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 19,
        "vendedor": "Guilherme",
        "numeroProposta": "08202547.0",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "11/08/2025",
        "dataFechamento": "11/08/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 20,
        "vendedor": "",
        "numeroProposta": "08202546.0",
        "cliente": "Método",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Matterport",
        "followUp": "21-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 10000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 21,
        "vendedor": "",
        "numeroProposta": "08202548.0",
        "cliente": "Projeto AMPR",
        "contato": "João Revel",
        "telefone": "",
        "email": "",
        "servico": "300 areas",
        "followUp": "21-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 100000.0,
        "probabilidade": "20%",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 22,
        "vendedor": "",
        "numeroProposta": "08202549.0",
        "cliente": "Metodo",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Vitoria ES",
        "followUp": "21-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 24000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 23,
        "vendedor": "",
        "numeroProposta": "08202550.0",
        "cliente": "Alexandre",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "11-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 4800.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 24,
        "vendedor": "",
        "numeroProposta": "08202551.0",
        "cliente": "Parangua",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "20-ago.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 25000.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 25,
        "vendedor": "",
        "numeroProposta": "08202552.0",
        "cliente": "Mogi das Cruzes",
        "contato": "Tony",
        "telefone": "",
        "email": "",
        "servico": "Aerolevantamento LiDAR",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 19000.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 26,
        "vendedor": "",
        "numeroProposta": "08202553.0",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "25/08/2025",
        "dataFechamento": "25/08/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 27,
        "vendedor": "",
        "numeroProposta": "08202554.1",
        "cliente": "Joiville eta Guilherme",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Scan e lpc",
        "followUp": "1-set.",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 15000.0,
        "probabilidade": "60%",
        "status": "Pendente",
        "observacao": ""
    },
    {
        "id": 28,
        "vendedor": "",
        "numeroProposta": "09202555.0",
        "cliente": "Campo do tenente",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "LPC com lidar + produto",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 12500.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 29,
        "vendedor": "",
        "numeroProposta": "09202556.0",
        "cliente": "Campo do tenente",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 12500.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 30,
        "vendedor": "",
        "numeroProposta": "09202557.0",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "08/09/2025",
        "dataFechamento": "08/09/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 31,
        "vendedor": "",
        "numeroProposta": "09202558.0",
        "cliente": "Riachuell",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Marcel",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 35600.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 32,
        "vendedor": "",
        "numeroProposta": "09202559.0",
        "cliente": "Orion",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Orion",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 135600.0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 33,
        "vendedor": "",
        "numeroProposta": "09202560.1",
        "cliente": "Oliveira e Araujo",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 130000.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 34,
        "vendedor": "",
        "numeroProposta": "09202561.1",
        "cliente": "Gabriel Lubacheski",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 15129.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 35,
        "vendedor": "Guilherme",
        "numeroProposta": "09202564.2",
        "cliente": "UNILIVRE",
        "contato": "Rafaela",
        "telefone": "",
        "email": "",
        "servico": "Lidar e Modelo BIM",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "20/01/2026",
        "dataFechamento": "20/01/2026",
        "valor": 100000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 36,
        "vendedor": "",
        "numeroProposta": "09202565.0",
        "cliente": "Daniel Belintani",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 36200.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 37,
        "vendedor": "",
        "numeroProposta": "09202566.0",
        "cliente": "Gilson",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 15600.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 38,
        "vendedor": "",
        "numeroProposta": "10202567.0",
        "cliente": "Residencial Becker",
        "contato": "Francisco",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 14980.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 39,
        "vendedor": "",
        "numeroProposta": "10202568.0",
        "cliente": "Tony",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 11500.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 40,
        "vendedor": "",
        "numeroProposta": "10202569.0",
        "cliente": "CB Construções – 6º contrato",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "22/09/2025",
        "dataFechamento": "22/09",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 41,
        "vendedor": "",
        "numeroProposta": "10202570.0",
        "cliente": "Ivlyn Medianeira",
        "contato": "ivilyn",
        "telefone": "(41)99684-8294",
        "email": "",
        "servico": "LPC",
        "followUp": "",
        "localizacao": " Interior PR",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9800.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 42,
        "vendedor": "",
        "numeroProposta": "10202571.0",
        "cliente": "Umbelino",
        "contato": "Indicação Marcelo",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 2300.0,
        "probabilidade": "0%",
        "status": "Perdida",
        "observacao": ""
    },
    {
        "id": 43,
        "vendedor": "",
        "numeroProposta": "10202572.0",
        "cliente": "Jessé Alexandre",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 10400.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 44,
        "vendedor": "",
        "numeroProposta": "10202573.0",
        "cliente": "Leonardo Kaiser",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9800.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 45,
        "vendedor": "",
        "numeroProposta": "10202574.0",
        "cliente": "Bocaiuva do Sul",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9800.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 46,
        "vendedor": "",
        "numeroProposta": "",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "06/10/2025",
        "dataFechamento": "06/10/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 47,
        "vendedor": "",
        "numeroProposta": "10202575.0",
        "cliente": "Engetecnica",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9800.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 48,
        "vendedor": "",
        "numeroProposta": "10202576.0",
        "cliente": "HIPARC",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 14980.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 49,
        "vendedor": "",
        "numeroProposta": "10202577.0",
        "cliente": "Solar BR",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 14980.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 50,
        "vendedor": "",
        "numeroProposta": "10202578.0",
        "cliente": "Olimpo Arquitetura",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9800.0,
        "probabilidade": "20%",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 51,
        "vendedor": "",
        "numeroProposta": "10202579.0",
        "cliente": "Atlas Schindler do Brasil",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 129960.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 52,
        "vendedor": "",
        "numeroProposta": "10202580.0",
        "cliente": "Elaine",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 53,
        "vendedor": "",
        "numeroProposta": "",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "20/10/2025",
        "dataFechamento": "20/10/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 54,
        "vendedor": "",
        "numeroProposta": "11202581.0",
        "cliente": "Arcadis",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 55,
        "vendedor": "",
        "numeroProposta": "11202582.0",
        "cliente": "Six Detail",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "Scan Automotivo",
        "followUp": "",
        "localizacao": " Curitiba-PR",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 2600.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 56,
        "vendedor": "",
        "numeroProposta": "11202583.3",
        "cliente": "Construtora Fairbanks E Pilnik",
        "contato": "Prreenche ai cara",
        "telefone": "Prreenche ai cara",
        "email": "",
        "servico": "Scan to CAD",
        "followUp": "",
        "localizacao": " São Paulo-SP",
        "dataProposta": "21/11/2025",
        "dataFechamento": "",
        "valor": 11500.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 57,
        "vendedor": "",
        "numeroProposta": "",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "03/11/2025",
        "dataFechamento": "03/11/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 58,
        "vendedor": "",
        "numeroProposta": "11202586.0",
        "cliente": "Método Engenharia",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 59,
        "vendedor": "",
        "numeroProposta": "11202587.0",
        "cliente": "Franchetti",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 60,
        "vendedor": "",
        "numeroProposta": "",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "17/11/2025",
        "dataFechamento": "17/11/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 61,
        "vendedor": "",
        "numeroProposta": "12202591.0",
        "cliente": "KZEMOS",
        "contato": "MATHEOS",
        "telefone": "(11)99254-9349",
        "email": "",
        "servico": "Scan - RTC - Igreja",
        "followUp": "",
        "localizacao": " Rio De janeiro-RJ",
        "dataProposta": "15/12/2025",
        "dataFechamento": "",
        "valor": 6800.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 62,
        "vendedor": "",
        "numeroProposta": "12202592.0",
        "cliente": "Carrefour",
        "contato": "Tulio / Mirian",
        "telefone": "(62)98111-0554 / (11)98852-6657",
        "email": "",
        "servico": "Scan to CAD - Carrefour Cabral (lojas)",
        "followUp": "",
        "localizacao": "Curitiba-PR",
        "dataProposta": "09/12/2025",
        "dataFechamento": "09/01/2026",
        "valor": 3800.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 63,
        "vendedor": "",
        "numeroProposta": "",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "01/12/2025",
        "dataFechamento": "01/12/2025",
        "valor": 12000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 64,
        "vendedor": "",
        "numeroProposta": "12202593.0",
        "cliente": "Caio",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 65,
        "vendedor": "",
        "numeroProposta": "02202610.0",
        "cliente": "EAC Consultoria",
        "contato": "Eduardo Cabral",
        "telefone": "(41)99102-2602",
        "email": "",
        "servico": "Aerolevantamento LiDAR",
        "followUp": "",
        "localizacao": "Curitiba-PR",
        "dataProposta": "02/02/2026",
        "dataFechamento": "03/02/2026",
        "valor": 28600.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 66,
        "vendedor": "",
        "numeroProposta": "01202601.1",
        "cliente": "Fábio",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 67,
        "vendedor": "",
        "numeroProposta": "01202605.0",
        "cliente": "H&S",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 68,
        "vendedor": "",
        "numeroProposta": "01202606.0",
        "cliente": "KZEMOS",
        "contato": "MATHEOS",
        "telefone": "(11)99254-9349",
        "email": "",
        "servico": "Scan - RTC - Igreja",
        "followUp": "",
        "localizacao": " Belo Horizonte-MG",
        "dataProposta": "29/01/2026",
        "dataFechamento": "29/01/2026",
        "valor": 6500.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 69,
        "vendedor": "",
        "numeroProposta": "01202608.0",
        "cliente": "Guilherme Torres",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 25000.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 70,
        "vendedor": "",
        "numeroProposta": "02202609.0",
        "cliente": "Tony",
        "contato": "Tony",
        "telefone": "(11)99137-3952",
        "email": "",
        "servico": "Aerolevantamento LiDAR",
        "followUp": "",
        "localizacao": "Mogi das Cruzes",
        "dataProposta": "26/01/0202.",
        "dataFechamento": "03/02/2026",
        "valor": 11500.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 71,
        "vendedor": "",
        "numeroProposta": "02202611.0",
        "cliente": "KZEMOS",
        "contato": "MATHEOS",
        "telefone": "(11)99254-9349",
        "email": "",
        "servico": "Scan - RTC - Igreja",
        "followUp": "",
        "localizacao": "Curitiba-PR",
        "dataProposta": "09/02/2026",
        "dataFechamento": "09/02/2026",
        "valor": 5200.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 72,
        "vendedor": "",
        "numeroProposta": "02202612.0",
        "cliente": "H&S – Projeto 2026",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 350000.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 73,
        "vendedor": "",
        "numeroProposta": "02202613.1",
        "cliente": "Intertechne",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 164990.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 74,
        "vendedor": "Allana",
        "numeroProposta": "02202615.0",
        "cliente": "Estaleiro de Mauá",
        "contato": "Adson",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 19946.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 75,
        "vendedor": "Allana",
        "numeroProposta": "02202616.0",
        "cliente": "Dr Aldo Costa",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 17200.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 76,
        "vendedor": "",
        "numeroProposta": "02202617.0",
        "cliente": "Construtora Baggio",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 7100.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 77,
        "vendedor": "Guilherme",
        "numeroProposta": "02202618.0",
        "cliente": "Dr Alexandre Wood Branco",
        "contato": "Tatiane Nunes",
        "telefone": "(41)99742-4540",
        "email": "",
        "servico": "Scan Fachada",
        "followUp": "",
        "localizacao": " Curitiba-PR",
        "dataProposta": "19/02/2026",
        "dataFechamento": "19/02/2026",
        "valor": 5000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 78,
        "vendedor": "",
        "numeroProposta": "02202619.0",
        "cliente": "CLI",
        "contato": "Flavio",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 9600.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 79,
        "vendedor": "",
        "numeroProposta": "02202620.0",
        "cliente": "Sagat Engenharia",
        "contato": "",
        "telefone": "",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 10600.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 80,
        "vendedor": "",
        "numeroProposta": "02202621.0",
        "cliente": "Vitta",
        "contato": "Andrea Sidyr",
        "telefone": "41 9622-1552",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 7800.0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 81,
        "vendedor": "Marcelo",
        "numeroProposta": "lead",
        "cliente": "Luiz Volpatto Arq",
        "contato": "Joã Pedro Volpatto",
        "telefone": "41992331717",
        "email": "",
        "servico": "",
        "followUp": "",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 82,
        "vendedor": "Marcelo",
        "numeroProposta": "sem contrato",
        "cliente": "CB Engenharia",
        "contato": "Jonathas / Erasmo",
        "telefone": "(42)99108-5621 / (11)95577-8274",
        "email": "",
        "servico": "Locação de Obra",
        "followUp": "",
        "localizacao": " Guaratuba-PR",
        "dataProposta": "",
        "dataFechamento": "05/12/2025",
        "valor": 4000.0,
        "probabilidade": "100%",
        "status": "Fechada",
        "observacao": ""
    },
    {
        "id": 83,
        "vendedor": "Allana",
        "numeroProposta": "02202622.0",
        "cliente": "Luiza Chaves",
        "contato": "Luiza Chaves",
        "telefone": "",
        "email": "",
        "servico": "Levantamento Topografico",
        "followUp": "",
        "localizacao": "Paranágua- PR",
        "dataProposta": "24/02/2026",
        "dataFechamento": "",
        "valor": 11800.0,
        "probabilidade": "80%",
        "status": "Pendente",
        "observacao": ""
    },
    {
        "id": 84,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "HTB",
        "contato": "Malio",
        "telefone": "(11)91211-4702",
        "email": "",
        "servico": "Levantamento ",
        "followUp": "02/2026",
        "localizacao": "",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "50%",
        "status": "Enviada",
        "observacao": ""
    },
    {
        "id": 85,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "TFK Engenharia ",
        "contato": "Thiago Ribeiro",
        "telefone": "41 - 9225- 7770",
        "email": "",
        "servico": "",
        "followUp": "05 fevereiro",
        "localizacao": "Curitiba",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 86,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "Multicelli Construtora",
        "contato": "Rafael Malucelli ",
        "telefone": "41- 9854-1666",
        "email": "",
        "servico": "",
        "followUp": "05 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 87,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "RZW Engenharia ",
        "contato": "Rodrigo Wierzbicki ",
        "telefone": "41 - 3209- 4139",
        "email": "rodrigo@rzwengenharia.com.br",
        "servico": "",
        "followUp": "10 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 88,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "Avana Engenharia",
        "contato": "Joilson José",
        "telefone": "41- 9655- 1898",
        "email": "",
        "servico": "",
        "followUp": "11 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 89,
        "vendedor": "Allana ",
        "numeroProposta": "Lead",
        "cliente": "Convexa Engenharia ",
        "contato": "Larissa Carneiro",
        "telefone": "41- 99914- 5053",
        "email": "engenharia@convexaengenharia.com.br",
        "servico": "",
        "followUp": "11 fevereiro",
        "localizacao": "Curitiba",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 90,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "A.S Ramos",
        "contato": "Carlos/ Samanta",
        "telefone": "47- 3345- 4792",
        "email": "compras@asramos.com.br",
        "servico": "",
        "followUp": "12 fevereiro",
        "localizacao": "Balneário Camboriú ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 91,
        "vendedor": "Allana ",
        "numeroProposta": "Lead",
        "cliente": "CGL Empreendimentos",
        "contato": "Rafael",
        "telefone": "47- 3335- 8292",
        "email": "suprimentos@cgl.com.br",
        "servico": "",
        "followUp": "12 fevereiro",
        "localizacao": "Balneário Camboriú ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 92,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "Mineração  Teixeira ",
        "contato": "Zamir Teixeira",
        "telefone": "61- 98133-8079",
        "email": "",
        "servico": "",
        "followUp": "04 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 93,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "ALSV Florestal",
        "contato": "André Veiga",
        "telefone": "41- 3408- 4920",
        "email": "",
        "servico": "",
        "followUp": "04 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "",
        "status": "Lead",
        "observacao": ""
    },
    {
        "id": 94,
        "vendedor": "Allana",
        "numeroProposta": "Lead",
        "cliente": "CL Engenharia",
        "contato": "Luciana takahashi",
        "telefone": "41- 98857- 2951",
        "email": "",
        "servico": "",
        "followUp": "05 fevereiro",
        "localizacao": "Curitiba ",
        "dataProposta": "",
        "dataFechamento": "",
        "valor": 0,
        "probabilidade": "70%",
        "status": "Pendente",
        "observacao": ""
    },
    {
        "id": 97,
        "vendedor": "Rafaela",
        "numeroProposta": "",
        "cliente": "TESTE AUTOMÁTICO",
        "contato": "Teste",
        "telefone": "teste@teste.com",
        "email": "",
        "servico": "Teste de Sincronização",
        "followUp": "",
        "localizacao": "Curitiba",
        "dataProposta": "24/02/2026",
        "dataFechamento": "",
        "valor": 1000.0,
        "probabilidade": "20%",
        "status": "Lead",
        "observacao": ""
    }
];

const stats = {
    total: 95,
    status: {"Fechada": 25, "Pendente": 5, "Perdida": 11, "Enviada": 14, "Lead": 42},
    ultimaAtualizacao: '2026-02-24T18:49:31.621423'
};
