// Dados do CRM - Restaurado v10.1
window.propostas = [
    {
        "id":  1,
        "rowIndex":  2,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "1",
        "cliente":  "Vanessa Guimarães",
        "contato":  "Vanessa",
        "telefoneEmail":  "41 99906 5076",
        "email":  "",
        "servico":  "Tour Virtual",
        "ultimoFollowup":  "",
        "localizacao":  "Fernandes Pinheiro",
        "dataProposta":  "27/02/2025",
        "dataFechamento":  "27/02/2025",
        "valor":  3500,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  2,
        "rowIndex":  3,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "05202530.0",
        "cliente":  "Ivilyn",
        "contato":  "ivilyn",
        "telefoneEmail":  "(41)99684-8294",
        "email":  "",
        "servico":  "Scan To BIM",
        "ultimoFollowup":  "21-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  35000,
        "probabilidade":  "60%",
        "observacao":  "Pendente",
        "status":  "Pendente"
    },
    {
        "id":  3,
        "rowIndex":  4,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "06202531.0",
        "cliente":  "André Canoas",
        "contato":  "André Canoas",
        "telefoneEmail":  "(11)97150-6623",
        "email":  "",
        "servico":  "LPC com lidar + produto",
        "ultimoFollowup":  "13-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  19980,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  4,
        "rowIndex":  5,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "06202532.0",
        "cliente":  "Max Pilarzinho",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento e Laudo",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  15980,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  5,
        "rowIndex":  6,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "06202534.0",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "28/07/2025",
        "dataFechamento":  "28/07/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  6,
        "rowIndex":  7,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "6202533.0",
        "cliente":  "Palacete do pinho",
        "contato":  "Renato Barbizan",
        "telefoneEmail":  "(41)99712-9402",
        "email":  "",
        "servico":  "Scan To BIM",
        "ultimoFollowup":  "",
        "localizacao":  " Irati-PR",
        "dataProposta":  "",
        "dataFechamento":  "2025-08-29T03:00:00.000Z",
        "valor":  38000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  7,
        "rowIndex":  8,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "7202535.0",
        "cliente":  "Priscila",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento Abranches",
        "ultimoFollowup":  "16-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  4800,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  8,
        "rowIndex":  9,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "7202536.0",
        "cliente":  "Amanda",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Prédio Guaira",
        "ultimoFollowup":  "16-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  23000,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  9,
        "rowIndex":  10,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "072025.38.0",
        "cliente":  "Cidatec",
        "contato":  "Marcelo",
        "telefoneEmail":  "N/A",
        "email":  "",
        "servico":  "Voo + cadastro de Vaga",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  3800,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  10,
        "rowIndex":  11,
        "isLocal":  false,
        "vendedor":  "Allana ",
        "numeroProposta":  "07202539.1",
        "cliente":  "Ana Paula Arquiteta",
        "contato":  "Ana Paula",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Scan To BIM",
        "ultimoFollowup":  "13-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  21705,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  11,
        "rowIndex":  12,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "7202537.0",
        "cliente":  "Acompanhamento Museu",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "22-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  3980,
        "probabilidade":  "60%",
        "observacao":  "Pendente",
        "status":  "Pendente"
    },
    {
        "id":  12,
        "rowIndex":  13,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "7202540.0",
        "cliente":  "Estudo de massa",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Estudo de massa",
        "ultimoFollowup":  "25-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  6880,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  13,
        "rowIndex":  14,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "7202537.0",
        "cliente":  "Topografica Santa Candida",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento topografico",
        "ultimoFollowup":  "24-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  3200,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  14,
        "rowIndex":  15,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "07202541.0",
        "cliente":  "Potencial S.A",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento topografico",
        "ultimoFollowup":  "31-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  135000,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  15,
        "rowIndex":  16,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "07202542.1",
        "cliente":  "Encompi",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento topografico",
        "ultimoFollowup":  "28-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  5000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  16,
        "rowIndex":  17,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "07202543.0",
        "cliente":  "Patricia",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento Chacará 3 Meninos",
        "ultimoFollowup":  "29-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  8000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  17,
        "rowIndex":  18,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "07202544.0",
        "cliente":  "Ricardo",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Campo Magro",
        "ultimoFollowup":  "29-jul.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  7000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  18,
        "rowIndex":  19,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "08202545.0",
        "cliente":  "Oliveira e Araujo",
        "contato":  "Alisson Caliman",
        "telefoneEmail":  "(62)99449-6145",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  " Hospital -Ponta Grossa",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  13800,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  19,
        "rowIndex":  20,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "08202547.0",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "11/08/2025",
        "dataFechamento":  "11/08/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  20,
        "rowIndex":  21,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202546.0",
        "cliente":  "Método",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Matterport",
        "ultimoFollowup":  "21-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  10000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  21,
        "rowIndex":  22,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202548.0",
        "cliente":  "Projeto AMPR",
        "contato":  "João Revel",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "300 areas",
        "ultimoFollowup":  "21-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  100000,
        "probabilidade":  "20%",
        "observacao":  "Lead",
        "status":  "Pendente"
    },
    {
        "id":  22,
        "rowIndex":  23,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202549.0",
        "cliente":  "Metodo",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Vitoria ES",
        "ultimoFollowup":  "21-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  24000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  23,
        "rowIndex":  24,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202550.0",
        "cliente":  "Alexandre",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "11-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  4800,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  24,
        "rowIndex":  25,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202551.0",
        "cliente":  "Parangua",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "20-ago.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  25000,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  25,
        "rowIndex":  26,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202552.0",
        "cliente":  "Mogi das Cruzes",
        "contato":  "Tony",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Aerolevantamento LiDAR",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  19000,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  26,
        "rowIndex":  27,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202553.0",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "25/08/2025",
        "dataFechamento":  "25/08/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  27,
        "rowIndex":  28,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "08202554.1",
        "cliente":  "Joiville eta Guilherme",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Scan e lpc",
        "ultimoFollowup":  "1-set.",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  15000,
        "probabilidade":  "60%",
        "observacao":  "Pendente",
        "status":  "Pendente"
    },
    {
        "id":  28,
        "rowIndex":  29,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202555.0",
        "cliente":  "Campo do tenente",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "LPC com lidar + produto",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  12500,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  29,
        "rowIndex":  30,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202556.0",
        "cliente":  "Campo do tenente",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  12500,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  30,
        "rowIndex":  31,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202557.0",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "08/09/2025",
        "dataFechamento":  "08/09/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  31,
        "rowIndex":  32,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202558.0",
        "cliente":  "Riachuell",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Marcel",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  35600,
        "probabilidade":  "50%",
        "observacao":  "Enviada",
        "status":  "Pendente"
    },
    {
        "id":  32,
        "rowIndex":  33,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "09202559.0",
        "cliente":  "Orion",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Orion",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  135600,
        "probabilidade":  0.5,
        "observacao":  "Enviada",
        "status":  "Perdida"
    },
    {
        "id":  33,
        "rowIndex":  34,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202560.1",
        "cliente":  "Oliveira e Araujo",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  130000,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  34,
        "rowIndex":  35,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202561.1",
        "cliente":  "Gabriel Lubacheski",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  15129,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  35,
        "rowIndex":  36,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "09202564.2",
        "cliente":  "UNILIVRE",
        "contato":  "Rafaela",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Lidar e Modelo BIM",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "20/01/2026",
        "dataFechamento":  "20/01/2026",
        "valor":  100000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  36,
        "rowIndex":  37,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202565.0",
        "cliente":  "Daniel Belintani",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  36200,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  37,
        "rowIndex":  38,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "09202566.0",
        "cliente":  "Gilson",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  15600,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  38,
        "rowIndex":  39,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202567.0",
        "cliente":  "Residencial Becker",
        "contato":  "Francisco",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  14980,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  39,
        "rowIndex":  40,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202568.0",
        "cliente":  "Tony",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  11500,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  40,
        "rowIndex":  41,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202569.0",
        "cliente":  "CB Construções – 6º contrato",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "22/09/2025",
        "dataFechamento":  "22/09",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  41,
        "rowIndex":  42,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202570.0",
        "cliente":  "Ivlyn Medianeira",
        "contato":  "ivilyn",
        "telefoneEmail":  "(41)99684-8294",
        "email":  "",
        "servico":  "LPC",
        "ultimoFollowup":  "",
        "localizacao":  " Interior PR",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9800,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  42,
        "rowIndex":  43,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202571.0",
        "cliente":  "Umbelino",
        "contato":  "Indicação Marcelo",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  2300,
        "probabilidade":  "0%",
        "observacao":  "Perdida",
        "status":  "Perdida"
    },
    {
        "id":  43,
        "rowIndex":  44,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202572.0",
        "cliente":  "Jessé Alexandre",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  10400,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  44,
        "rowIndex":  45,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202573.0",
        "cliente":  "Leonardo Kaiser",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9800,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  45,
        "rowIndex":  46,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202574.0",
        "cliente":  "Bocaiuva do Sul",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9800,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  46,
        "rowIndex":  47,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "06/10/2025",
        "dataFechamento":  "06/10/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  47,
        "rowIndex":  48,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202575.0",
        "cliente":  "Engetecnica",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9800,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  48,
        "rowIndex":  49,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202576.0",
        "cliente":  "HIPARC",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  14980,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  49,
        "rowIndex":  50,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202577.0",
        "cliente":  "Solar BR",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  14980,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  50,
        "rowIndex":  51,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "10202578.0",
        "cliente":  "Olimpo Arquitetura",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9800,
        "probabilidade":  "20%",
        "observacao":  "Lead",
        "status":  "Pendente"
    },
    {
        "id":  51,
        "rowIndex":  52,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202579.0",
        "cliente":  "Atlas Schindler do Brasil",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  129960,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  52,
        "rowIndex":  53,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "10202580.0",
        "cliente":  "Elaine",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  53,
        "rowIndex":  54,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "20/10/2025",
        "dataFechamento":  "20/10/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  54,
        "rowIndex":  55,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "11202581.0",
        "cliente":  "Arcadis",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  55,
        "rowIndex":  56,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "11202582.0",
        "cliente":  "Six Detail",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Scan Automotivo",
        "ultimoFollowup":  "",
        "localizacao":  " Curitiba-PR",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  2600,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  56,
        "rowIndex":  57,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "11202583.3",
        "cliente":  "Construtora Fairbanks E Pilnik",
        "contato":  "Prreenche ai cara",
        "telefoneEmail":  "Prreenche ai cara",
        "email":  "",
        "servico":  "Scan to CAD",
        "ultimoFollowup":  "",
        "localizacao":  " São Paulo-SP",
        "dataProposta":  "21/11/2025",
        "dataFechamento":  "",
        "valor":  11500,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  57,
        "rowIndex":  58,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "03/11/2025",
        "dataFechamento":  "03/11/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  58,
        "rowIndex":  59,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "11202586.0",
        "cliente":  "Método Engenharia",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  59,
        "rowIndex":  60,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "11202587.0",
        "cliente":  "Franchetti",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  60,
        "rowIndex":  61,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "17/11/2025",
        "dataFechamento":  "17/11/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  61,
        "rowIndex":  62,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "12202591.0",
        "cliente":  "KZEMOS",
        "contato":  "MATHEOS",
        "telefoneEmail":  "(11)99254-9349",
        "email":  "",
        "servico":  "Scan - RTC - Igreja",
        "ultimoFollowup":  "",
        "localizacao":  " Rio De janeiro-RJ",
        "dataProposta":  "15/12/2025",
        "dataFechamento":  "",
        "valor":  6800,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  62,
        "rowIndex":  63,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "12202592.0",
        "cliente":  "Carrefour",
        "contato":  "Tulio / Mirian",
        "telefoneEmail":  "(62)98111-0554 / (11)98852-6657",
        "email":  "",
        "servico":  "Scan to CAD - Carrefour Cabral (lojas)",
        "ultimoFollowup":  "",
        "localizacao":  "Curitiba-PR",
        "dataProposta":  "09/12/2025",
        "dataFechamento":  "09/01/2026",
        "valor":  3800,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  63,
        "rowIndex":  64,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "01/12/2025",
        "dataFechamento":  "01/12/2025",
        "valor":  12000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  64,
        "rowIndex":  65,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "12202593.0",
        "cliente":  "Caio",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  65,
        "rowIndex":  66,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202610.0",
        "cliente":  "EAC Consultoria",
        "contato":  "Eduardo Cabral",
        "telefoneEmail":  "(41)99102-2602",
        "email":  "",
        "servico":  "Aerolevantamento LiDAR",
        "ultimoFollowup":  "",
        "localizacao":  "Curitiba-PR",
        "dataProposta":  "02/02/2026",
        "dataFechamento":  "03/02/2026",
        "valor":  28600,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  66,
        "rowIndex":  67,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "01202601.1",
        "cliente":  "Fábio",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  67,
        "rowIndex":  68,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "01202605.0",
        "cliente":  "H\u0026S",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  68,
        "rowIndex":  69,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "01202606.0",
        "cliente":  "KZEMOS",
        "contato":  "MATHEOS",
        "telefoneEmail":  "(11)99254-9349",
        "email":  "",
        "servico":  "Scan - RTC - Igreja",
        "ultimoFollowup":  "",
        "localizacao":  " Belo Horizonte-MG",
        "dataProposta":  "29/01/2026",
        "dataFechamento":  "29/01/2026",
        "valor":  6500,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  69,
        "rowIndex":  70,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "01202608.0",
        "cliente":  "Guilherme Torres",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  25000,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  70,
        "rowIndex":  71,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202609.0",
        "cliente":  "Tony",
        "contato":  "Tony",
        "telefoneEmail":  "(11)99137-3952",
        "email":  "",
        "servico":  "Aerolevantamento LiDAR",
        "ultimoFollowup":  "",
        "localizacao":  "Mogi das Cruzes",
        "dataProposta":  "26/01/0202.",
        "dataFechamento":  "03/02/2026",
        "valor":  11500,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  71,
        "rowIndex":  72,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202611.0",
        "cliente":  "KZEMOS",
        "contato":  "MATHEOS",
        "telefoneEmail":  "(11)99254-9349",
        "email":  "",
        "servico":  "Scan - RTC - Igreja",
        "ultimoFollowup":  "",
        "localizacao":  "Curitiba-PR",
        "dataProposta":  "09/02/2026",
        "dataFechamento":  "09/02/2026",
        "valor":  5200,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  72,
        "rowIndex":  73,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202612.0",
        "cliente":  "H\u0026S – Projeto 2026",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  350000,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  73,
        "rowIndex":  74,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202613.1",
        "cliente":  "Intertechne",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  164990,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  74,
        "rowIndex":  75,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "02202615.0",
        "cliente":  "Estaleiro de Mauá",
        "contato":  "Adson",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  19946,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  75,
        "rowIndex":  76,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "02202616.0",
        "cliente":  "Dr Aldo Costa",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  17200,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  76,
        "rowIndex":  77,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202617.0",
        "cliente":  "Construtora Baggio",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  7100,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  77,
        "rowIndex":  78,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "02202618.0",
        "cliente":  "Dr Alexandre Wood Branco",
        "contato":  "Tatiane Nunes",
        "telefoneEmail":  "(41)99742-4540",
        "email":  "",
        "servico":  "Scan Fachada",
        "ultimoFollowup":  "",
        "localizacao":  " Curitiba-PR",
        "dataProposta":  "19/02/2026",
        "dataFechamento":  "19/02/2026",
        "valor":  5000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  78,
        "rowIndex":  79,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202619.0",
        "cliente":  "CLI",
        "contato":  "Flavio",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  9600,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  79,
        "rowIndex":  80,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202620.0",
        "cliente":  "Sagat Engenharia",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  10600,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  80,
        "rowIndex":  81,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "02202621.0",
        "cliente":  "Vitta",
        "contato":  "Andrea Sidyr",
        "telefoneEmail":  "41 9622-1552",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  7800,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  81,
        "rowIndex":  82,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "lead",
        "cliente":  "Luiz Volpatto Arq",
        "contato":  "Joã Pedro Volpatto",
        "telefoneEmail":  "41992331717",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  82,
        "rowIndex":  83,
        "isLocal":  false,
        "vendedor":  "Marcelo",
        "numeroProposta":  "sem contrato",
        "cliente":  "CB Engenharia",
        "contato":  "Jonathas / Erasmo",
        "telefoneEmail":  "(42)99108-5621 / (11)95577-8274",
        "email":  "",
        "servico":  "Locação de Obra",
        "ultimoFollowup":  "",
        "localizacao":  " Guaratuba-PR",
        "dataProposta":  "",
        "dataFechamento":  "05/12/2025",
        "valor":  4000,
        "probabilidade":  "100%",
        "observacao":  "Fechada",
        "status":  "Fechada"
    },
    {
        "id":  83,
        "rowIndex":  84,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "02202622.0",
        "cliente":  "Luiza Chaves",
        "contato":  "Luiza Chaves",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Levantamento Topografico",
        "ultimoFollowup":  "",
        "localizacao":  "Paranágua- PR",
        "dataProposta":  "24/02/2026",
        "dataFechamento":  "",
        "valor":  11800,
        "probabilidade":  "80%",
        "observacao":  "Pendente",
        "status":  "Pendente"
    },
    {
        "id":  84,
        "rowIndex":  85,
        "isLocal":  false,
        "vendedor":  "Guilherme",
        "numeroProposta":  "Novo Lead",
        "cliente":  "Porto belo ",
        "contato":  "Elissa",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Topografia ",
        "ultimoFollowup":  "",
        "localizacao":  "Porto belo",
        "dataProposta":  "2026-02-24T03:00:00.000Z",
        "dataFechamento":  "2025-03-24T03:00:00.000Z",
        "valor":  8500,
        "probabilidade":  0.2,
        "observacao":  "Enviar proposta ",
        "status":  "Perdida"
    },
    {
        "id":  85,
        "rowIndex":  86,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "TFK Engenharia ",
        "contato":  "Thiago Ribeiro",
        "telefoneEmail":  "41 - 9225- 7770",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "05 fevereiro",
        "localizacao":  "Curitiba",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  86,
        "rowIndex":  87,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "Multicelli Construtora",
        "contato":  "Rafael Malucelli ",
        "telefoneEmail":  "41- 9854-1666",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "05 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  87,
        "rowIndex":  88,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "RZW Engenharia ",
        "contato":  "Rodrigo Wierzbicki ",
        "telefoneEmail":  "41 - 3209- 4139",
        "email":  "rodrigo@rzwengenharia.com.br",
        "servico":  "",
        "ultimoFollowup":  "10 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  88,
        "rowIndex":  89,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "Avana Engenharia",
        "contato":  "Joilson José",
        "telefoneEmail":  "41- 9655- 1898",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "11 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  89,
        "rowIndex":  90,
        "isLocal":  false,
        "vendedor":  "Allana ",
        "numeroProposta":  "Lead",
        "cliente":  "Convexa Engenharia ",
        "contato":  "Larissa Carneiro",
        "telefoneEmail":  "41- 99914- 5053",
        "email":  "engenharia@convexaengenharia.com.br",
        "servico":  "",
        "ultimoFollowup":  "11 fevereiro",
        "localizacao":  "Curitiba",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  90,
        "rowIndex":  91,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "A.S Ramos",
        "contato":  "Carlos/ Samanta",
        "telefoneEmail":  "47- 3345- 4792",
        "email":  "compras@asramos.com.br",
        "servico":  "",
        "ultimoFollowup":  "12 fevereiro",
        "localizacao":  "Balneário Camboriú ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  91,
        "rowIndex":  92,
        "isLocal":  false,
        "vendedor":  "Allana ",
        "numeroProposta":  "Lead",
        "cliente":  "CGL Empreendimentos",
        "contato":  "Rafael",
        "telefoneEmail":  "47- 3335- 8292",
        "email":  "suprimentos@cgl.com.br",
        "servico":  "",
        "ultimoFollowup":  "12 fevereiro",
        "localizacao":  "Balneário Camboriú ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  92,
        "rowIndex":  93,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "Mineração  Teixeira ",
        "contato":  "Zamir Teixeira",
        "telefoneEmail":  "61- 98133-8079",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "04 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  93,
        "rowIndex":  94,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "ALSV Florestal",
        "contato":  "André Veiga",
        "telefoneEmail":  "41- 3408- 4920",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "04 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  94,
        "rowIndex":  95,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "CL Engenharia",
        "contato":  "Luciana takahashi",
        "telefoneEmail":  "41- 98857- 2951",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "05 fevereiro",
        "localizacao":  "Curitiba ",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "70%",
        "observacao":  "Pendente",
        "status":  "Pendente"
    },
    {
        "id":  95,
        "rowIndex":  96,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  96,
        "rowIndex":  97,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "Lead",
        "cliente":  "",
        "contato":  "",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "Lead",
        "status":  "Perdida"
    },
    {
        "id":  97,
        "rowIndex":  98,
        "isLocal":  false,
        "vendedor":  "Rafaela",
        "numeroProposta":  "",
        "cliente":  "TESTE AUTOMÁTICO",
        "contato":  "Teste",
        "telefoneEmail":  "teste@teste.com",
        "email":  "",
        "servico":  "Teste de Sincronização",
        "ultimoFollowup":  "",
        "localizacao":  "Curitiba",
        "dataProposta":  "24/02/2026",
        "dataFechamento":  "",
        "valor":  1000,
        "probabilidade":  "20%",
        "observacao":  "Lead",
        "status":  "Pendente"
    },
    {
        "id":  98,
        "rowIndex":  99,
        "isLocal":  false,
        "vendedor":  "Allana",
        "numeroProposta":  "02202623.0",
        "cliente":  "Porto Belo",
        "contato":  "Elissa",
        "telefoneEmail":  "",
        "email":  "",
        "servico":  "Diaria topografia e escaner",
        "ultimoFollowup":  "2026-02-24T03:00:00.000Z",
        "localizacao":  "Porto Belo",
        "dataProposta":  "2026-02-24T03:00:00.000Z",
        "dataFechamento":  "2026-03-24T03:00:00.000Z",
        "valor":  8500,
        "probabilidade":  0.2,
        "observacao":  "",
        "status":  "Perdida"
    },
    {
        "id":  99,
        "rowIndex":  100,
        "isLocal":  false,
        "vendedor":  "",
        "numeroProposta":  "",
        "cliente":  "",
        "contato":  "",
        "telefoneEmail":  " ",
        "email":  "",
        "servico":  "",
        "ultimoFollowup":  "",
        "localizacao":  "",
        "dataProposta":  "",
        "dataFechamento":  "",
        "valor":  0,
        "probabilidade":  "",
        "observacao":  "",
        "status":  "Perdida"
    }
];
