propostas = [
{id:2,vendedor:"Marcelo",cliente:"ivilyn",empresa:"ivilyn",servico:"21-ago.",data:"R$35.000,00",valor:0,status:"Perdida"},
{id:3,vendedor:"Marcelo",cliente:"André Canoas",empresa:"André",servico:"13-ago.",data:"R$19.980,00",valor:0,status:"Perdida"},
{id:5,vendedor:"Guilherme",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:6,vendedor:"",cliente:"Renato Barbizan",empresa:"Renato",servico:"",data:"R$38.000,00",valor:0,status:"Fechada"},
{id:9,vendedor:"",cliente:"Marcelo",empresa:"Marcelo",servico:"",data:"R$3.800,00",valor:0,status:"Perdida"},
{id:18,vendedor:"",cliente:"Alisson Caliman",empresa:"Alisson",servico:"",data:"R$13.800,00",valor:0,status:"Perdida"},
{id:19,vendedor:"Guilherme",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:21,vendedor:"",cliente:"João Revel",empresa:"João",servico:"21-ago.",data:"",valor:0,status:"Perdida"},
{id:25,vendedor:"",cliente:"Tony",empresa:"Tony",servico:"",data:"R$19.000,00",valor:0,status:"Perdida"},
{id:26,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:30,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:40,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:41,vendedor:"",cliente:"ivilyn",empresa:"ivilyn",servico:"",data:"R$9.800,00",valor:0,status:"Perdida"},
{id:42,vendedor:"",cliente:"Indicação Marcelo",empresa:"Indicação",servico:"",data:"R$2.300,00",valor:0,status:"Perdida"},
{id:46,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:53,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:56,vendedor:"",cliente:"Prreenche ai cara",empresa:"Prreenche",servico:"",data:"R$11.500,00",valor:0,status:"Perdida"},
{id:57,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:60,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:61,vendedor:"",cliente:"MATHEOS",empresa:"MATHEOS",servico:"",data:"R$6.800,00",valor:0,status:"Perdida"},
{id:62,vendedor:"",cliente:"Tulio / Mirian",empresa:"Tulio",servico:"",data:"R$3.800,00",valor:0,status:"Perdida"},
{id:63,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$12.000,00",valor:0,status:"Pendente"},
{id:65,vendedor:"",cliente:"Eduardo Cabral",empresa:"Eduardo",servico:"",data:"R$28.600,00",valor:0,status:"Perdida"},
{id:68,vendedor:"",cliente:"MATHEOS",empresa:"MATHEOS",servico:"",data:"R$6.500,00",valor:0,status:"Perdida"},
{id:70,vendedor:"",cliente:"Tony",empresa:"Tony",servico:"",data:"R$11.500,00",valor:0,status:"Perdida"},
{id:71,vendedor:"",cliente:"MATHEOS",empresa:"MATHEOS",servico:"",data:"R$5.200,00",valor:0,status:"Perdida"},
{id:77,vendedor:"Allana",cliente:"Tatiane Nunes",empresa:"Tatiane",servico:"",data:"R$5.000,00",valor:0,status:"Perdida"},
{id:80,vendedor:"",cliente:"Andrea Sidyr",empresa:"Andrea",servico:"",data:"R$7.800,00",valor:0,status:"Perdida"},
{id:81,vendedor:"",cliente:"Joã Pedro Volpatto",empresa:"Joã",servico:"",data:"",valor:0,status:"Perdida"},
{id:82,vendedor:"",cliente:"Jonathas / Erasmo",empresa:"Jonathas",servico:"",data:"R$4.000,00",valor:0,status:"Pendente"},
{id:83,vendedor:"Allana",cliente:"Luiza Chaves",empresa:"Luiza",servico:"",data:"",valor:0,status:"Perdida"},
];